server {
	listen 8080;
	server_name local1;
	client_max_body_size 1000;

	location / {
		root www;
		allowed_methods GET;
	}
}
server {
	listen 8081;
	server_name local2;
	client_max_body_size 1000;

	location / {
		root www/tests;
		allowed_methods GET;
	}
}
