server {
	listen 8080;
	server_name alpha.local;
	client_max_body_size 1048576;

	location / {
		root www;
		index index.html;
		allowed_methods GET;
	}

	location /old/ {
		return 301 /;
	}
}

server {
	listen 8080;
	server_name beta.local;
	client_max_body_size 1048576;

	location / {
		root www/tests;
		index index.html;
		allowed_methods GET;
	}

	location /old/ {
		return 302 /;
	}
}
