server {
	listen 8080;
	server_name home-orange;
	client_max_body_size 1048576;

	error_page 404 /errors/404.html;

	location / {
		root www/virtual_hosts/home-orange;
		index index.html;
		autoindex off;
		allowed_methods GET;
	}

	location /home/ {
		root www/home;
		allowed_methods GET;
	}
}

server {
	listen 8080;
	server_name home-green;
	client_max_body_size 1048576;

	error_page 404 /errors/404.html;

	location / {
		root www/virtual_hosts/home-green;
		index index.html;
		autoindex off;
		allowed_methods GET;
	}

	location /home/ {
		root www/home;
		allowed_methods GET;
	}
}
